bookkeeper_manager:
    resource: "@BookkeeperManagerBundle/Resources/config/routing.yml"
    prefix:   /

bookkeeper_hello_world:
    resource: "@BookkeeperHelloWorldBundle/Resources/config/routing.yml"
    prefix:   /book

app:
    resource: @AppBundle/Controller/
    type:     annotation
